### ISSUE TITLE
Items on many user pages aren't fetched after a certain point

### ISSUE THREAD

**Issue by Kerobyte** [HookedBehemoth/pixiv-proxy#2]
Example 1:  ~18 missing
https://www.pixiv.net/en/users/1499614/artworks?p=3
Example 2: ~54 missing
https://www.pixiv.net/en/users/83739/artworks?p=9
Example 3: ~23 missing
https://www.pixiv.net/en/users/51516034/artworks?p=2

**Comment by HookedBehemoth** [comment]
https://github.com/HookedBehemoth/pixiv-proxy/commit/6b7affb4d56d99c1839f23ae73a55131aa8d92dc
